import { useState } from 'react';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { Dropdown } from './Dropdown';
import { Button } from '../Button/Button';
import { ButtonIcon } from '../ButtonIcon/ButtonIcon';
import { documentActions } from './menu-examples';
import { selectionDocs } from '../../docs/selection-components';
const meta={title:'Components/Selection/Dropdown',component:Dropdown,tags:['autodocs','ready'],parameters:{layout:'padded',docs:{description:{component:selectionDocs('Dropdown')}}},args:{items:documentActions,children:<Button>Действия</Button>},argTypes:{placement:{control:'select',options:['auto','top','bottom']},matchWidth:{control:'boolean'},searchable:{control:'boolean'},closeOnSelect:{control:'boolean'}}} satisfies Meta<typeof Dropdown>;
export default meta;type Story=StoryObj<typeof meta>;
export const Default:Story={render:function Demo(args){const [result,setResult]=useState('');return <><Dropdown {...args} onAction={item=>setResult(String(item.title))}/><p role="status">{result&&`Действие: ${result}`}</p><Button color="secondary">Следующая кнопка</Button></>;}};
export const IconTrigger:Story={name:'От кнопки с иконкой',args:{children:<ButtonIcon icon="more-horisontal" aria-label="Действия с документом"/>}};
export const Searchable:Story={name:'Поиск по меню',args:{searchable:true}};
export const AtEdge:Story={name:'У края экрана',decorators:[Story=><div style={{height:'calc(100vh - 48px)',display:'flex',alignItems:'flex-end',justifyContent:'flex-end'}}><Story/></div>]};
export const Disabled:Story={args:{children:<Button disabled>Действия</Button>}};
