import type { Meta, StoryObj } from '@storybook/react-vite';
import { Menu } from './Menu';
import { Button } from '../Button/Button';
import { documentActions } from './menu-examples';
import { selectionDocs } from '../../docs/selection-components';
const meta={title:'Components/Selection/Menu',component:Menu,tags:['autodocs','ready'],parameters:{layout:'padded',docs:{description:{component:selectionDocs('Menu')}}},args:{items:documentActions,'aria-label':'Действия с документом'},decorators:[Story=><div style={{width:'100%',maxWidth:456}}><Story/></div>],argTypes:{searchable:{control:'boolean'},skeleton:{control:'boolean'},maxHeight:{control:'number'}}} satisfies Meta<typeof Menu>;
export default meta;type Story=StoryObj<typeof meta>;
export const Default:Story={};
export const SearchAndScroll:Story={args:{searchable:true,items:Array.from({length:30},(_,i)=>({id:String(i),title:`Документ ${i+1}`,description:'Описание документа'})),footer:<><Button size="small" color="tertiary">Отменить</Button><Button size="small">Выбрать</Button></>}};
export const Selection:Story={args:{role:'listbox',selectedId:'one',items:[{id:'one',title:'Первый',selection:'check'},{id:'two',title:'Второй',selection:'check'},{id:'three',title:'Третий',selection:'check',disabled:true}]}};
export const OneItem:Story={args:{items:[{id:'one',title:'Единственный пункт'}]}};
export const Skeleton:Story={args:{skeleton:true,searchable:true}};
