import { useRef, useState, type DragEvent, type HTMLAttributes } from 'react';
import { Button } from '../Button/Button'; import { Icon } from '../Icon/Icon'; import './Dropzone.css';
export type DropzoneState='default'|'hover'|'pressed'|'disabled'|'error'|'success';
export type DropzoneAlign='left'|'center';
export interface DropzoneProps extends Omit<HTMLAttributes<HTMLDivElement>,'onDrop'> {state?:DropzoneState;align?:DropzoneAlign;accept?:string;multiple?:boolean;formats?:string;maxQuantity?:number;maxFileSize?:string;maxTotalSize?:string;showFormats?:boolean;showMaxQuantity?:boolean;showMaxFileSize?:boolean;showMaxTotalSize?:boolean;onFiles?:(files:File[])=>void}
export function Dropzone({state='default',align='left',accept,multiple=true,formats='.doc, .docx, .xls, .xlsx, .pdf, .jpg, .jpeg, .png',maxQuantity=10,maxFileSize='15 МБ',maxTotalSize='50 МБ',showFormats=true,showMaxQuantity=false,showMaxFileSize=true,showMaxTotalSize=false,onFiles,className='',...props}:DropzoneProps){
 const input=useRef<HTMLInputElement>(null); const [drag,setDrag]=useState(false); const disabled=state==='disabled'; const active=drag?'drag-over':state;
 const emit=(list:FileList|null)=>{if(!disabled&&list)onFiles?.(Array.from(list))}; const drop=(e:DragEvent)=>{e.preventDefault();setDrag(false);emit(e.dataTransfer.files)};
 return <div {...props} className={`fdoc-dropzone fdoc-dropzone--${align} fdoc-dropzone--${active} ${className}`} onClick={()=>!disabled&&input.current?.click()} onDragOver={e=>{e.preventDefault();if(!disabled)setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={drop} data-testid="dropzone" aria-disabled={disabled}>
  <input ref={input} className="fdoc-dropzone__input" type="file" accept={accept} multiple={multiple} disabled={disabled} onChange={e=>emit(e.target.files)}/>
  {align==='left'?<><span className="fdoc-dropzone__icon"><Icon name="doc-paper" size={24}/></span><div className="fdoc-dropzone__content"><strong>Перетащите файлы сюда, чтобы начать загрузку</strong><Requirements {...{formats,maxQuantity,maxFileSize,maxTotalSize,showFormats,showMaxQuantity,showMaxFileSize,showMaxTotalSize}}/></div></>:<div className="fdoc-dropzone__center"><Button size="medium" color="primary" iconLeft="plus" disabled={disabled} tabIndex={-1}>Выбрать файл</Button><span>или перетащите файлы сюда</span><Requirements {...{formats,maxQuantity,maxFileSize,maxTotalSize,showFormats,showMaxQuantity,showMaxFileSize,showMaxTotalSize}}/></div>}
 </div>;
}
function Requirements(p:{formats:string;maxQuantity:number;maxFileSize:string;maxTotalSize:string;showFormats:boolean;showMaxQuantity:boolean;showMaxFileSize:boolean;showMaxTotalSize:boolean}){return <div className="fdoc-dropzone__requirements">{p.showFormats&&<span>Допустимые форматы:<br/>{p.formats}</span>}{p.showMaxQuantity&&<span>Максимальное количество файлов — {p.maxQuantity}</span>}{p.showMaxFileSize&&<span>Максимальный размер файла — {p.maxFileSize}</span>}{p.showMaxTotalSize&&<span>Максимальный общий размер файлов — {p.maxTotalSize}</span>}</div>}
