import { useEffect,useId,useLayoutEffect,useRef,useState,type ButtonHTMLAttributes,type ReactNode } from 'react';
import { Icon,type IconName } from '../Icon/Icon';
import { Badge } from '../Badge/Badge';
import { Skeleton } from '../Skeleton/Skeleton';
import './Tabs.css';
export interface TabProps extends ButtonHTMLAttributes<HTMLButtonElement> { selected?:boolean; icon?:IconName; badge?:ReactNode; state?:'default'|'hover'|'focused'|'pressed'|'disabled'|'skeleton'; }
export function Tab({selected=false,icon,badge,state='default',disabled=false,children,className='',...props}:TabProps) {
 const inactive=disabled||state==='disabled';const content=<>{icon&&<span className="fdoc-tab__icon"><Icon name={icon} size={24}/></span>}{children!=null&&<span className="fdoc-tab__label">{children}</span>}{badge!=null&&<span className="fdoc-tab__badge"><Badge size="small" state={inactive?'disabled':'default'}>{badge}</Badge></span>}</>;
 if(state==='skeleton')return <span className={`fdoc-tab ${className}`} data-icon-only={children==null} aria-hidden="true">{icon&&<span className="fdoc-tab__icon"><Skeleton width={24} height={24} shape="icon"/></span>}{children!=null&&<span className="fdoc-tab__label"><Skeleton width={56} shape="text" textSize="body"/></span>}{badge!=null&&<span className="fdoc-tab__badge"><Badge size="small" state="skeleton"/></span>}</span>;
 return <button {...props} type="button" role="tab" aria-selected={selected} disabled={inactive} data-icon-only={children==null} data-state={inactive?'disabled':state} className={`fdoc-tab ${className}`}>{content}</button>;
}
export interface TabItem { value:string; label?:ReactNode; ariaLabel?:string; icon?:IconName; badge?:ReactNode; disabled?:boolean; content:ReactNode; }
export interface TabsProps { items:TabItem[]; value?:string; defaultValue?:string; onValueChange?:(value:string)=>void; 'aria-label':string; className?:string; isLoading?:boolean; }
export function Tabs({items,value,defaultValue,onValueChange,'aria-label':label,className='',isLoading=false}:TabsProps) {
 const id=useId();const [local,setLocal]=useState(defaultValue);const active=items.some(x=>x.value===(value??local))?(value??local):items.find(x=>!x.disabled)?.value;const [focusValue,setFocusValue]=useState(active);const list=useRef<HTMLDivElement>(null);const [scroll,setScroll]=useState({overflow:false,left:false,right:false});
 const refresh=()=>{const el=list.current;if(el)setScroll({overflow:el.scrollWidth>el.clientWidth+1,left:el.scrollLeft>1,right:el.scrollLeft+el.clientWidth<el.scrollWidth-1});};
 useLayoutEffect(()=>{refresh();const observer=new ResizeObserver(refresh);if(list.current){observer.observe(list.current);Array.from(list.current.children).forEach(el=>observer.observe(el));}return()=>observer.disconnect();},[items,isLoading]);
 const reveal=(el:HTMLElement|null)=>{const root=list.current;if(!root||!el)return;const a=root.getBoundingClientRect(),b=el.getBoundingClientRect();if(b.left<a.left)root.scrollLeft-=a.left-b.left;else if(b.right>a.right)root.scrollLeft+=b.right-a.right;};
 useEffect(()=>{setFocusValue(active);reveal(document.getElementById(`${id}-tab-${items.findIndex(x=>x.value===active)}`));},[active,id]);
 const enabled=items.filter(x=>!x.disabled);const focused=enabled.some(x=>x.value===focusValue)?focusValue:enabled[0]?.value;
 return <div className={`fdoc-tabs ${className}`}><div className="fdoc-tabs__bar">{scroll.overflow&&<button type="button" className="fdoc-tabs__arrow" aria-label="Прокрутить вкладки влево" disabled={!scroll.left} onClick={()=>{list.current?.scrollBy({left:-list.current.clientWidth*.7});}}><Icon name="arrow-chevron-left" size={24}/></button>}<div ref={list} role="tablist" aria-label={label} className="fdoc-tabs__list" onScroll={refresh} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocusValue(active);}}>{items.map((item,i)=><Tab key={item.value} id={`${id}-tab-${i}`} aria-controls={`${id}-panel-${i}`} aria-label={item.ariaLabel} selected={item.value===active} disabled={item.disabled} icon={item.icon} badge={item.badge} state={isLoading?'skeleton':'default'} tabIndex={focused===item.value?0:-1} onFocus={()=>setFocusValue(item.value)} onClick={()=>{if(item.value===active)return;if(value===undefined)setLocal(item.value);onValueChange?.(item.value);}} onKeyDown={e=>{let delta=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0;if(!delta&&e.key!=='Home'&&e.key!=='End')return;e.preventDefault();const at=enabled.findIndex(x=>x.value===item.value);const next=e.key==='Home'?enabled[0]:e.key==='End'?enabled.at(-1)!:enabled[(at+delta+enabled.length)%enabled.length];if(!next)return;const el=document.getElementById(`${id}-tab-${items.indexOf(next)}`);el?.focus();reveal(el);}}>{item.label}</Tab>)}</div>{scroll.overflow&&<button type="button" className="fdoc-tabs__arrow" aria-label="Прокрутить вкладки вправо" disabled={!scroll.right} onClick={()=>{list.current?.scrollBy({left:list.current.clientWidth*.7});}}><Icon name="arrow-chevron-right" size={24}/></button>}</div>{!isLoading&&items.map((item,i)=><div key={item.value} id={`${id}-panel-${i}`} role="tabpanel" aria-labelledby={`${id}-tab-${i}`} hidden={item.value!==active} tabIndex={0} className="fdoc-tabs__panel">{item.content}</div>)}</div>;
}
