import { describe,it,expect,vi } from 'vitest';
import { render,screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { axe } from 'jest-axe';
import { Chips } from './Chips';
import { ChipsGroup } from './ChipsGroup';

const options=[{value:'a',text:'Договоры'},{value:'b',text:'Архив',disabled:true},{value:'c',text:'Акты'}];
describe('Chips',()=>{
  it('renders a status as text without a focusable action',()=>{render(<Chips text="Подписан" color="success" iconLeft="check_circle"/>);expect(screen.queryByRole('button')).not.toBeInTheDocument();expect(screen.getByTestId('chips')).toHaveAttribute('data-color','success');});
  it('toggles with Enter and Space and restores the unselected surface',async()=>{const user=userEvent.setup();render(<Chips text="Договоры" color="base" defaultSelected={false}/>);const button=screen.getByRole('button');await user.tab();expect(button).toHaveFocus();await user.keyboard('{Enter}');expect(button).toHaveAttribute('aria-pressed','true');expect(screen.getByTestId('chips')).toHaveAttribute('data-color','primary');await user.keyboard(' ');expect(button).toHaveAttribute('aria-pressed','false');expect(screen.getByTestId('chips')).toHaveAttribute('data-color','base');});
  it('waits for controlled selection props',async()=>{const user=userEvent.setup(),change=vi.fn();const {rerender}=render(<Chips text="Договоры" selected={false} onSelectedChange={change}/>);await user.click(screen.getByRole('button'));expect(change).toHaveBeenCalledWith(true);expect(screen.getByRole('button')).toHaveAttribute('aria-pressed','false');rerender(<Chips text="Договоры" selected onSelectedChange={change}/>);expect(screen.getByRole('button')).toHaveAttribute('aria-pressed','true');});
  it('keeps removal separate from selection and exposes its accessible name',async()=>{const user=userEvent.setup(),remove=vi.fn(),change=vi.fn();const {container}=render(<Chips text="Договоры" defaultSelected onSelectedChange={change} onRemove={remove}/>);expect(container.querySelector('button button')).toBeNull();await user.tab();await user.tab();expect(screen.getByRole('button',{name:'Удалить: Договоры'})).toHaveFocus();await user.keyboard('{Enter}');expect(remove).toHaveBeenCalledOnce();expect(change).not.toHaveBeenCalled();expect((await axe(container)).violations).toEqual([]);});
  it('disables both actions and excludes them from Tab',async()=>{const user=userEvent.setup(),remove=vi.fn(),change=vi.fn();render(<Chips text="Договоры" selected disabled onSelectedChange={change} onRemove={remove}/>);for(const button of screen.getAllByRole('button')){expect(button).toBeDisabled();await user.click(button);}await user.tab();expect(document.activeElement).toBe(document.body);expect(remove).not.toHaveBeenCalled();expect(change).not.toHaveBeenCalled();});
  it('renders skeleton without content or actions',()=>{render(<Chips text="Договоры" state="skeleton" selected onRemove={()=>{}}/>);expect(screen.queryByRole('button')).not.toBeInTheDocument();expect(screen.queryByText('Договоры')).not.toBeInTheDocument();expect(screen.getByTestId('chips')).toHaveAttribute('aria-hidden','true');});
});
describe('ChipsGroup',()=>{
  it('moves focus past disabled options without selecting and toggles independently',async()=>{const user=userEvent.setup(),change=vi.fn();render(<ChipsGroup aria-label="Типы" options={options} defaultValue={['a']} onValueChange={change}/>);await user.tab();expect(screen.getByRole('button',{name:'Договоры'})).toHaveFocus();await user.keyboard('{ArrowRight}');expect(screen.getByRole('button',{name:'Акты'})).toHaveFocus();expect(change).not.toHaveBeenCalled();await user.keyboard(' ');expect(change).toHaveBeenLastCalledWith(['a','c']);await user.keyboard('{Home}{Enter}');expect(change).toHaveBeenLastCalledWith(['c']);});
  it('replaces single selection and allows clearing it',async()=>{const user=userEvent.setup(),change=vi.fn();render(<ChipsGroup options={options} defaultValue={['a']} selectionMode="single" onValueChange={change}/>);await user.click(screen.getByRole('button',{name:'Акты'}));expect(change).toHaveBeenLastCalledWith(['c']);expect(screen.getByRole('button',{name:'Договоры'})).toHaveAttribute('aria-pressed','false');await user.click(screen.getByRole('button',{name:'Акты'}));expect(change).toHaveBeenLastCalledWith([]);});
  it('preserves controlled value and has an accessible group',async()=>{const user=userEvent.setup(),change=vi.fn();const {container}=render(<ChipsGroup aria-label="Типы" options={options} value={['a']} onValueChange={change}/>);await user.click(screen.getByRole('button',{name:'Акты'}));expect(change).toHaveBeenLastCalledWith(['a','c']);expect(screen.getByRole('button',{name:'Акты'})).toHaveAttribute('aria-pressed','false');expect((await axe(container)).violations).toEqual([]);});
});
