export type TokenValue = string | number;
export type TokenEntry = { readonly token: string; readonly value: TokenValue; readonly reference?: string };

export const primitiveColorTokens = [
{ token: "--neutral-25", value: "#f8f8f9" },
{ token: "--neutral-50", value: "#dddee0" },
{ token: "--neutral-100", value: "#cfd1d3" },
{ token: "--neutral-200", value: "#b4b6ba" },
{ token: "--neutral-300", value: "#8b8e95" },
{ token: "--neutral-400", value: "#70747c" },
{ token: "--neutral-500", value: "#555963" },
{ token: "--neutral-600", value: "#474b53" },
{ token: "--neutral-700", value: "#3a3d43" },
{ token: "--neutral-800", value: "#25272c" },
{ token: "--neutral-900", value: "#18191c" },
{ token: "--neutral-transparent-04", value: "#5559630a" },
{ token: "--neutral-transparent-08", value: "#55596314" },
{ token: "--neutral-transparent-16", value: "#55596329" },
{ token: "--neutral-transparent-24", value: "#5559633d" },
{ token: "--neutral-transparent-32", value: "#55596352" },
{ token: "--neutral-transparent-40", value: "#55596366" },
{ token: "--neutral-transparent-48", value: "#5559637a" },
{ token: "--yellow-25", value: "#fffef5" },
{ token: "--yellow-50", value: "#fff8cc" },
{ token: "--yellow-100", value: "#fff5b8" },
{ token: "--yellow-200", value: "#fff08f" },
{ token: "--yellow-300", value: "#ffe752" },
{ token: "--yellow-400", value: "#ffe229" },
{ token: "--yellow-500", value: "#ffdc00" },
{ token: "--yellow-600", value: "#d6b900" },
{ token: "--yellow-700", value: "#ad9600" },
{ token: "--yellow-800", value: "#706100" },
{ token: "--yellow-900", value: "#473e00" },
{ token: "--yellow-transparent-04", value: "#ffdc000a" },
{ token: "--yellow-transparent-08", value: "#ffdc0014" },
{ token: "--yellow-transparent-16", value: "#ffdc0029" },
{ token: "--yellow-transparent-24", value: "#ffdc003d" },
{ token: "--yellow-transparent-32", value: "#ffdc0052" },
{ token: "--yellow-transparent-40", value: "#ffdc0066" },
{ token: "--yellow-transparent-48", value: "#ffdc007a" },
{ token: "--green-25", value: "#f6fcf7" },
{ token: "--green-50", value: "#d3f0d9" },
{ token: "--green-100", value: "#c2eac9" },
{ token: "--green-200", value: "#9fdeab" },
{ token: "--green-300", value: "#6bcd7c" },
{ token: "--green-400", value: "#48c15e" },
{ token: "--green-500", value: "#25b53f" },
{ token: "--green-600", value: "#1f9835" },
{ token: "--green-700", value: "#197b2b" },
{ token: "--green-800", value: "#10501c" },
{ token: "--green-900", value: "#0a3312" },
{ token: "--green-transparent-04", value: "#25b53f0a" },
{ token: "--green-transparent-08", value: "#25b53f14" },
{ token: "--green-transparent-16", value: "#25b53f29" },
{ token: "--green-transparent-24", value: "#25b53f3d" },
{ token: "--green-transparent-32", value: "#25b53f52" },
{ token: "--green-transparent-40", value: "#25b53f66" },
{ token: "--green-transparent-48", value: "#25b53f7a" },
{ token: "--red-25", value: "#fef5f8" },
{ token: "--red-50", value: "#f9ccdb" },
{ token: "--red-100", value: "#f6b8cd" },
{ token: "--red-200", value: "#f18fb1" },
{ token: "--red-300", value: "#ea5286" },
{ token: "--red-400", value: "#e52969" },
{ token: "--red-500", value: "#e0004d" },
{ token: "--red-600", value: "#bc0041" },
{ token: "--red-700", value: "#980034" },
{ token: "--red-800", value: "#630022" },
{ token: "--red-900", value: "#3f0016" },
{ token: "--red-transparent-04", value: "#e0004d0a" },
{ token: "--red-transparent-08", value: "#e0004d14" },
{ token: "--red-transparent-16", value: "#e0004d29" },
{ token: "--red-transparent-24", value: "#e0004d3d" },
{ token: "--red-transparent-32", value: "#e0004d52" },
{ token: "--red-transparent-40", value: "#e0004d66" },
{ token: "--red-transparent-48", value: "#e0004d7a" },
{ token: "--purple-25", value: "#f7f6fc" },
{ token: "--purple-50", value: "#d9d0ef" },
{ token: "--purple-100", value: "#cabde8" },
{ token: "--purple-200", value: "#ac97db" },
{ token: "--purple-300", value: "#7f5ec8" },
{ token: "--purple-400", value: "#6138bb" },
{ token: "--purple-500", value: "#4312ae" },
{ token: "--purple-600", value: "#380f92" },
{ token: "--purple-700", value: "#2e0c76" },
{ token: "--purple-800", value: "#1d084d" },
{ token: "--purple-900", value: "#130531" },
{ token: "--purple-transparent-04", value: "#4312ae0a" },
{ token: "--purple-transparent-08", value: "#4312ae14" },
{ token: "--purple-transparent-16", value: "#4312ae29" },
{ token: "--purple-transparent-24", value: "#4312ae3d" },
{ token: "--purple-transparent-32", value: "#4312ae52" },
{ token: "--purple-transparent-40", value: "#4312ae66" },
{ token: "--purple-transparent-48", value: "#4312ae7a" },
{ token: "--orange-25", value: "#fff9f5" },
{ token: "--orange-50", value: "#fee1cc" },
{ token: "--orange-100", value: "#fed5b8" },
{ token: "--orange-200", value: "#fdbd8f" },
{ token: "--orange-300", value: "#fc9952" },
{ token: "--orange-400", value: "#fb8129" },
{ token: "--orange-500", value: "#fa6900" },
{ token: "--orange-600", value: "#d25800" },
{ token: "--orange-700", value: "#aa4700" },
{ token: "--orange-800", value: "#6e2e00" },
{ token: "--orange-900", value: "#461d00" },
{ token: "--orange-transparent-04", value: "#fa69000a" },
{ token: "--orange-transparent-08", value: "#fa690014" },
{ token: "--orange-transparent-16", value: "#fa690029" },
{ token: "--orange-transparent-24", value: "#fa69003d" },
{ token: "--orange-transparent-32", value: "#fa690052" },
{ token: "--orange-transparent-40", value: "#fa690066" },
{ token: "--orange-transparent-48", value: "#fa69007a" },
{ token: "--violet-25", value: "#fbfafb" },
{ token: "--black-25-04", value: "#0000000a" },
{ token: "--white-25-04", value: "#ffffff0a" },
{ token: "--white-50-08", value: "#ffffff14" },
{ token: "--white-100-16", value: "#ffffff29" },
{ token: "--white-200-24", value: "#ffffff3d" },
{ token: "--white-300-32", value: "#ffffff52" },
{ token: "--white-400-40", value: "#ffffff66" },
{ token: "--white-500-48", value: "#ffffff7a" },
{ token: "--white-600-56", value: "#ffffff8f" },
{ token: "--white-700-64", value: "#ffffffa3" },
{ token: "--white-800-72", value: "#ffffffb8" },
{ token: "--white-900-80", value: "#ffffffcc" },
{ token: "--white-1000", value: "#ffffff" },
{ token: "--black-50-08", value: "#00000014" },
{ token: "--black-100-16", value: "#00000029" },
{ token: "--black-200-24", value: "#0000003d" },
{ token: "--black-300-32", value: "#00000052" },
{ token: "--black-400-40", value: "#00000066" },
{ token: "--black-500-48", value: "#0000007a" },
{ token: "--black-600-56", value: "#0000008f" },
{ token: "--black-700-64", value: "#000000a3" },
{ token: "--black-800-72", value: "#000000b8" },
{ token: "--black-900-80", value: "#000000cc" },
{ token: "--black-1000", value: "#000000" },
{ token: "--violet-50", value: "#ece4ed" },
{ token: "--violet-100", value: "#e4d9e6" },
{ token: "--violet-200", value: "#d4c4d7" },
{ token: "--violet-300", value: "#bda3c1" },
{ token: "--violet-400", value: "#ae8eb3" },
{ token: "--violet-500", value: "#9e78a4" },
{ token: "--violet-600", value: "#85658a" },
{ token: "--violet-700", value: "#6b5270" },
{ token: "--violet-800", value: "#463548" },
{ token: "--violet-900", value: "#2c222e" },
{ token: "--violet-transparent-04", value: "#9e78a40a" },
{ token: "--violet-transparent-08", value: "#9e78a414" },
{ token: "--violet-transparent-16", value: "#9e78a429" },
{ token: "--violet-transparent-24", value: "#9e78a43d" },
{ token: "--violet-transparent-32", value: "#9e78a452" },
{ token: "--violet-transparent-40", value: "#9e78a466" },
{ token: "--violet-transparent-48", value: "#9e78a47a" },
{ token: "--client-25", value: "#f7f6ff" },
{ token: "--client-50", value: "#d5d4ff" },
{ token: "--client-100", value: "#c5c2ff" },
{ token: "--client-200", value: "#a3a0ff" },
{ token: "--client-300", value: "#726bff" },
{ token: "--client-400", value: "#5049ff" },
{ token: "--client-500", value: "#2f26ff" },
{ token: "--client-600", value: "#2720d6" },
{ token: "--client-700", value: "#201aad" },
{ token: "--client-800", value: "#151170" },
{ token: "--client-900", value: "#0d0b47" },
{ token: "--client-transparent-04", value: "#2f26ff0a" },
{ token: "--client-transparent-08", value: "#2f26ff14" },
{ token: "--client-transparent-16", value: "#2f26ff29" },
{ token: "--client-transparent-24", value: "#2f26ff3d" },
{ token: "--client-transparent-32", value: "#2f26ff52" },
{ token: "--client-transparent-40", value: "#2f26ff66" },
{ token: "--client-transparent-48", value: "#2f26ff7a" }
] as const;

export const semanticColorTokens = [
{ token: "--background-base-default", value: "#ffffff", reference: "--white-1000" },
{ token: "--background-base-secondary", value: "#f8f8f9", reference: "--neutral-25" },
{ token: "--background-base-default-hover", value: "#dddee0", reference: "--neutral-50" },
{ token: "--background-base-default-pressed", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--background-base-default-disabled", value: "#ffffff", reference: "--white-1000" },
{ token: "--background-base-secondary-hover", value: "#dddee0", reference: "--neutral-50" },
{ token: "--background-base-secondary-pressed", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--background-base-secondary-disabled", value: "#f8f8f9", reference: "--neutral-25" },
{ token: "--background-base-tertiary", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--background-base-tertiary-hover", value: "#dddee0", reference: "--neutral-50" },
{ token: "--background-base-tertiary-pressed", value: "#f8f8f9", reference: "--neutral-25" },
{ token: "--background-base-tertiary-disabled", value: "#f8f8f9", reference: "--neutral-25" },
{ token: "--background-base-inverse", value: "#25272c", reference: "--neutral-800" },
{ token: "--background-base-inverse-light", value: "#474b53", reference: "--neutral-600" },
{ token: "--background-base-skeleton", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--background-base-inverse-hover", value: "#3a3d43", reference: "--neutral-700" },
{ token: "--background-base-inverse-pressed", value: "#474b53", reference: "--neutral-600" },
{ token: "--background-base-inverse-disabled", value: "#70747c", reference: "--neutral-400" },
{ token: "--background-primary-default", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--background-primary-secondary", value: "#fffef5", reference: "--yellow-25" },
{ token: "--background-primary-tertiary", value: "#fff08f", reference: "--yellow-200" },
{ token: "--background-success-default", value: "#25b53f", reference: "--green-500" },
{ token: "--background-primary-inverse", value: "#473e00", reference: "--yellow-900" },
{ token: "--background-primary-default-hover", value: "#ffe229", reference: "--yellow-400" },
{ token: "--background-primary-secondary-hover", value: "#fff8cc", reference: "--yellow-50" },
{ token: "--background-success-default-hover", value: "#48c15e", reference: "--green-400" },
{ token: "--background-success-default-pressed", value: "#6bcd7c", reference: "--green-300" },
{ token: "--background-primary-tertiary-hover", value: "#fff5b8", reference: "--yellow-100" },
{ token: "--background-primary-inverse-hover", value: "#706100", reference: "--yellow-800" },
{ token: "--background-success-default-disabled", value: "#c2eac9", reference: "--green-100" },
{ token: "--background-success-secondary", value: "#f6fcf7", reference: "--green-25" },
{ token: "--background-primary-secondary-pressed", value: "#fff5b8", reference: "--yellow-100" },
{ token: "--background-primary-tertiary-pressed", value: "#fff8cc", reference: "--yellow-50" },
{ token: "--background-primary-inverse-pressed", value: "#ad9600", reference: "--yellow-700" },
{ token: "--background-success-secondary-hover", value: "#d3f0d9", reference: "--green-50" },
{ token: "--background-primary-default-pressed", value: "#ffe752", reference: "--yellow-300" },
{ token: "--background-success-secondary-pressed", value: "#c2eac9", reference: "--green-100" },
{ token: "--background-primary-default-disabled", value: "#fff5b8", reference: "--yellow-100" },
{ token: "--background-success-secondary-disabled", value: "#f6fcf7", reference: "--green-25" },
{ token: "--background-primary-secondary-disabled", value: "#fffef5", reference: "--yellow-25" },
{ token: "--background-success-tertiary", value: "#9fdeab", reference: "--green-200" },
{ token: "--background-primary-tertiary-disabled", value: "#fff8cc", reference: "--yellow-50" },
{ token: "--background-success-tertiary-hover", value: "#c2eac9", reference: "--green-100" },
{ token: "--background-primary-inverse-disabled", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--background-success-tertiary-pressed", value: "#d3f0d9", reference: "--green-50" },
{ token: "--background-success-tertiary-disabled", value: "#d3f0d9", reference: "--green-50" },
{ token: "--background-error-default", value: "#e0004d", reference: "--red-500" },
{ token: "--background-error-default-hover", value: "#e52969", reference: "--red-400" },
{ token: "--background-error-default-pressed", value: "#ea5286", reference: "--red-300" },
{ token: "--background-error-default-disabled", value: "#f6b8cd", reference: "--red-100" },
{ token: "--background-error-secondary", value: "#fef5f8", reference: "--red-25" },
{ token: "--background-error-secondary-hover", value: "#f9ccdb", reference: "--red-50" },
{ token: "--background-error-secondary-pressed", value: "#f6b8cd", reference: "--red-100" },
{ token: "--background-error-secondary-disabled", value: "#fef5f8", reference: "--red-25" },
{ token: "--background-error-tertiary", value: "#f18fb1", reference: "--red-200" },
{ token: "--background-success-inverse", value: "#0a3312", reference: "--green-900" },
{ token: "--background-accent-default", value: "#4312ae", reference: "--purple-500" },
{ token: "--background-error-tertiary-hover", value: "#f6b8cd", reference: "--red-100" },
{ token: "--background-accent-default-hover", value: "#6138bb", reference: "--purple-400" },
{ token: "--background-success-inverse-hover", value: "#10501c", reference: "--green-800" },
{ token: "--background-accent-default-pressed", value: "#7f5ec8", reference: "--purple-300" },
{ token: "--background-error-tertiary-pressed", value: "#f9ccdb", reference: "--red-50" },
{ token: "--background-success-inverse-pressed", value: "#197b2b", reference: "--green-700" },
{ token: "--background-error-tertiary-disabled", value: "#f9ccdb", reference: "--red-50" },
{ token: "--background-accent-default-disabled", value: "#cabde8", reference: "--purple-100" },
{ token: "--background-success-inverse-disabled", value: "#25b53f", reference: "--green-500" },
{ token: "--background-error-inverse", value: "#3f0016", reference: "--red-900" },
{ token: "--background-error-inverse-hover", value: "#630022", reference: "--red-800" },
{ token: "--background-error-inverse-pressed", value: "#980034", reference: "--red-700" },
{ token: "--background-error-inverse-disabled", value: "#e0004d", reference: "--red-500" },
{ token: "--background-accent-secondary", value: "#f7f6fc", reference: "--purple-25" },
{ token: "--background-accent-secondary-hover", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--background-accent-secondary-pressed", value: "#cabde8", reference: "--purple-100" },
{ token: "--background-accent-secondary-disabled", value: "#f7f6fc", reference: "--purple-25" },
{ token: "--background-accent-tertiary", value: "#ac97db", reference: "--purple-200" },
{ token: "--background-accent-tertiary-hover", value: "#cabde8", reference: "--purple-100" },
{ token: "--background-accent-tertiary-pressed", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--background-accent-tertiary-disabled", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--background-accent-inverse", value: "#130531", reference: "--purple-900" },
{ token: "--background-accent-inverse-hover", value: "#1d084d", reference: "--purple-800" },
{ token: "--background-accent-inverse-pressed", value: "#2e0c76", reference: "--purple-700" },
{ token: "--background-accent-inverse-disabled", value: "#4312ae", reference: "--purple-500" },
{ token: "--background-warning-default", value: "#fa6900", reference: "--orange-500" },
{ token: "--background-warning-default-hover", value: "#fb8129", reference: "--orange-400" },
{ token: "--background-warning-default-pressed", value: "#fc9952", reference: "--orange-300" },
{ token: "--background-warning-default-disabled", value: "#fed5b8", reference: "--orange-100" },
{ token: "--background-warning-secondary", value: "#fff9f5", reference: "--orange-25" },
{ token: "--background-warning-secondary-hover", value: "#fee1cc", reference: "--orange-50" },
{ token: "--background-warning-secondary-pressed", value: "#fed5b8", reference: "--orange-100" },
{ token: "--background-warning-secondary-disabled", value: "#fff9f5", reference: "--orange-25" },
{ token: "--background-warning-tertiary", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--background-warning-tertiary-hover", value: "#fed5b8", reference: "--orange-100" },
{ token: "--background-warning-tertiary-pressed", value: "#fee1cc", reference: "--orange-50" },
{ token: "--background-warning-tertiary-disabled", value: "#fee1cc", reference: "--orange-50" },
{ token: "--background-warning-inverse", value: "#461d00", reference: "--orange-900" },
{ token: "--background-warning-inverse-hover", value: "#6e2e00", reference: "--orange-800" },
{ token: "--background-warning-inverse-pressed", value: "#aa4700", reference: "--orange-700" },
{ token: "--background-warning-inverse-disabled", value: "#fa6900", reference: "--orange-500" },
{ token: "--text-base-default", value: "#18191c", reference: "--neutral-900" },
{ token: "--text-base-default-hover", value: "#25272c", reference: "--neutral-800" },
{ token: "--text-base-default-pressed", value: "#3a3d43", reference: "--neutral-700" },
{ token: "--text-base-default-disabled", value: "#70747c", reference: "--neutral-400" },
{ token: "--text-base-default-light", value: "#3a3d43", reference: "--neutral-700" },
{ token: "--text-base-default-light-hover", value: "#474b53", reference: "--neutral-600" },
{ token: "--text-base-default-light-pressed", value: "#555963", reference: "--neutral-500" },
{ token: "--text-base-default-light-disabled", value: "#70747c", reference: "--neutral-400" },
{ token: "--text-base-secondary", value: "#70747c", reference: "--neutral-400" },
{ token: "--text-base-secondary-hover", value: "#8b8e95", reference: "--neutral-300" },
{ token: "--text-base-secondary-pressed", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--text-base-secondary-disabled", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--text-base-inverse", value: "#dddee0", reference: "--neutral-50" },
{ token: "--text-base-inverse-hover", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--text-base-inverse-pressed", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--text-base-inverse-disabled", value: "#dddee0", reference: "--neutral-50" },
{ token: "--text-base-inverse-secondary", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--text-base-white", value: "#ffffff", reference: "--white-1000" },
{ token: "--text-base-inverse-secondary-hover", value: "#8b8e95", reference: "--neutral-300" },
{ token: "--text-base-inverse-secondary-pressed", value: "#70747c", reference: "--neutral-400" },
{ token: "--text-base-inverse-secondary-disabled", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--text-primary-default", value: "#473e00", reference: "--yellow-900" },
{ token: "--text-primary-default-hover", value: "#706100", reference: "--yellow-800" },
{ token: "--text-primary-default-pressed", value: "#ad9600", reference: "--yellow-700" },
{ token: "--text-primary-default-disabled", value: "#d6b900", reference: "--yellow-600" },
{ token: "--text-primary-default-light", value: "#ad9600", reference: "--yellow-700" },
{ token: "--text-primary-default-light-hover", value: "#d6b900", reference: "--yellow-600" },
{ token: "--text-primary-default-light-pressed", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--text-primary-default-light-disabled", value: "#ffe229", reference: "--yellow-400" },
{ token: "--text-primary-secondary", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--text-primary-secondary-hover", value: "#ffe229", reference: "--yellow-400" },
{ token: "--text-primary-secondary-pressed", value: "#ffe752", reference: "--yellow-300" },
{ token: "--text-primary-secondary-disabled", value: "#fff08f", reference: "--yellow-200" },
{ token: "--text-primary-inverse", value: "#fff8cc", reference: "--yellow-50" },
{ token: "--text-primary-inverse-hover", value: "#fff5b8", reference: "--yellow-100" },
{ token: "--text-primary-inverse-pressed", value: "#fff08f", reference: "--yellow-200" },
{ token: "--text-primary-inverse-disabled", value: "#fffef5", reference: "--yellow-25" },
{ token: "--text-primary-inverse-light", value: "#fff08f", reference: "--yellow-200" },
{ token: "--text-primary-inverse-light-hover", value: "#ffe752", reference: "--yellow-300" },
{ token: "--text-primary-inverse-light-pressed", value: "#ffe229", reference: "--yellow-400" },
{ token: "--text-primary-inverse-light-disabled", value: "#fff08f", reference: "--yellow-200" },
{ token: "--text-success-default", value: "#0a3312", reference: "--green-900" },
{ token: "--text-success-default-hover", value: "#10501c", reference: "--green-800" },
{ token: "--text-success-default-pressed", value: "#197b2b", reference: "--green-700" },
{ token: "--text-success-default-disabled", value: "#1f9835", reference: "--green-600" },
{ token: "--text-success-default-light", value: "#197b2b", reference: "--green-700" },
{ token: "--text-success-default-light-hover", value: "#1f9835", reference: "--green-600" },
{ token: "--text-success-default-light-pressed", value: "#25b53f", reference: "--green-500" },
{ token: "--text-success-default-light-disabled", value: "#48c15e", reference: "--green-400" },
{ token: "--text-success-secondary", value: "#25b53f", reference: "--green-500" },
{ token: "--text-success-secondary-hover", value: "#48c15e", reference: "--green-400" },
{ token: "--text-success-secondary-pressed", value: "#6bcd7c", reference: "--green-300" },
{ token: "--text-success-secondary-disabled", value: "#9fdeab", reference: "--green-200" },
{ token: "--text-success-inverse", value: "#d3f0d9", reference: "--green-50" },
{ token: "--text-success-inverse-hover", value: "#c2eac9", reference: "--green-100" },
{ token: "--text-success-inverse-pressed", value: "#9fdeab", reference: "--green-200" },
{ token: "--text-success-inverse-disabled", value: "#d3f0d9", reference: "--green-50" },
{ token: "--text-success-inverse-light", value: "#9fdeab", reference: "--green-200" },
{ token: "--text-success-inverse-light-hover", value: "#6bcd7c", reference: "--green-300" },
{ token: "--text-success-inverse-light-pressed", value: "#48c15e", reference: "--green-400" },
{ token: "--text-success-inverse-light-disabled", value: "#9fdeab", reference: "--green-200" },
{ token: "--text-error-default", value: "#3f0016", reference: "--red-900" },
{ token: "--text-error-default-hover", value: "#630022", reference: "--red-800" },
{ token: "--text-error-default-pressed", value: "#980034", reference: "--red-700" },
{ token: "--text-error-default-disabled", value: "#bc0041", reference: "--red-600" },
{ token: "--text-error-default-light", value: "#980034", reference: "--red-700" },
{ token: "--text-error-default-light-hover", value: "#bc0041", reference: "--red-600" },
{ token: "--text-error-default-light-pressed", value: "#e0004d", reference: "--red-500" },
{ token: "--text-error-default-light-disabled", value: "#e52969", reference: "--red-400" },
{ token: "--text-error-secondary", value: "#e0004d", reference: "--red-500" },
{ token: "--text-error-secondary-hover", value: "#e52969", reference: "--red-400" },
{ token: "--text-error-secondary-pressed", value: "#ea5286", reference: "--red-300" },
{ token: "--text-error-secondary-disabled", value: "#f18fb1", reference: "--red-200" },
{ token: "--text-error-inverse", value: "#f9ccdb", reference: "--red-50" },
{ token: "--text-error-inverse-hover", value: "#f6b8cd", reference: "--red-100" },
{ token: "--text-error-inverse-pressed", value: "#f18fb1", reference: "--red-200" },
{ token: "--text-error-inverse-disabled", value: "#f9ccdb", reference: "--red-50" },
{ token: "--text-error-inverse-light", value: "#f18fb1", reference: "--red-200" },
{ token: "--text-error-inverse-light-hover", value: "#ea5286", reference: "--red-300" },
{ token: "--text-error-inverse-light-pressed", value: "#e52969", reference: "--red-400" },
{ token: "--text-error-inverse-light-disabled", value: "#f18fb1", reference: "--red-200" },
{ token: "--text-accent-default", value: "#130531", reference: "--purple-900" },
{ token: "--text-accent-default-hover", value: "#1d084d", reference: "--purple-800" },
{ token: "--text-accent-default-pressed", value: "#2e0c76", reference: "--purple-700" },
{ token: "--text-accent-default-disabled", value: "#380f92", reference: "--purple-600" },
{ token: "--text-accent-default-light", value: "#2e0c76", reference: "--purple-700" },
{ token: "--text-accent-default-light-hover", value: "#380f92", reference: "--purple-600" },
{ token: "--text-accent-default-light-pressed", value: "#4312ae", reference: "--purple-500" },
{ token: "--text-accent-default-light-disabled", value: "#6138bb", reference: "--purple-400" },
{ token: "--text-accent-secondary", value: "#4312ae", reference: "--purple-500" },
{ token: "--text-accent-secondary-hover", value: "#6138bb", reference: "--purple-400" },
{ token: "--text-accent-secondary-pressed", value: "#7f5ec8", reference: "--purple-300" },
{ token: "--text-accent-secondary-disabled", value: "#ac97db", reference: "--purple-200" },
{ token: "--text-accent-inverse", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--text-accent-inverse-hover", value: "#cabde8", reference: "--purple-100" },
{ token: "--text-accent-inverse-pressed", value: "#ac97db", reference: "--purple-200" },
{ token: "--text-accent-inverse-disabled", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--text-accent-inverse-light", value: "#ac97db", reference: "--purple-200" },
{ token: "--text-accent-inverse-light-hover", value: "#7f5ec8", reference: "--purple-300" },
{ token: "--text-accent-inverse-light-pressed", value: "#6138bb", reference: "--purple-400" },
{ token: "--text-accent-inverse-light-disabled", value: "#ac97db", reference: "--purple-200" },
{ token: "--icon-base-default", value: "#18191c", reference: "--neutral-900" },
{ token: "--icon-base-default-hover", value: "#25272c", reference: "--neutral-800" },
{ token: "--icon-base-default-pressed", value: "#3a3d43", reference: "--neutral-700" },
{ token: "--icon-base-default-disabled", value: "#70747c", reference: "--neutral-400" },
{ token: "--icon-base-default-light", value: "#3a3d43", reference: "--neutral-700" },
{ token: "--icon-base-default-light-hover", value: "#474b53", reference: "--neutral-600" },
{ token: "--icon-base-default-light-pressed", value: "#555963", reference: "--neutral-500" },
{ token: "--icon-base-default-light-disabled", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--icon-base-secondary", value: "#70747c", reference: "--neutral-400" },
{ token: "--icon-base-secondary-hover", value: "#8b8e95", reference: "--neutral-300" },
{ token: "--icon-base-secondary-pressed", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--icon-base-secondary-disabled", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--icon-base-inverse", value: "#dddee0", reference: "--neutral-50" },
{ token: "--icon-base-inverse-hover", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--icon-base-inverse-pressed", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--icon-base-inverse-disabled", value: "#dddee0", reference: "--neutral-50" },
{ token: "--icon-base-inverse-secondary", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--icon-base-inverse-secondary-hover", value: "#8b8e95", reference: "--neutral-300" },
{ token: "--icon-base-inverse-secondary-pressed", value: "#70747c", reference: "--neutral-400" },
{ token: "--icon-base-inverse-secondary-disabled", value: "#b4b6ba", reference: "--neutral-200" },
{ token: "--icon-primary-default", value: "#473e00", reference: "--yellow-900" },
{ token: "--icon-primary-default-hover", value: "#706100", reference: "--yellow-800" },
{ token: "--icon-primary-default-pressed", value: "#ad9600", reference: "--yellow-700" },
{ token: "--icon-primary-default-disabled", value: "#d6b900", reference: "--yellow-600" },
{ token: "--icon-primary-default-light", value: "#ad9600", reference: "--yellow-700" },
{ token: "--icon-primary-default-light-hover", value: "#d6b900", reference: "--yellow-600" },
{ token: "--icon-primary-default-light-pressed", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--icon-primary-default-light-disabled", value: "#ffe229", reference: "--yellow-400" },
{ token: "--icon-primary-secondary", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--icon-primary-secondary-hover", value: "#ffe229", reference: "--yellow-400" },
{ token: "--icon-primary-secondary-pressed", value: "#ffe752", reference: "--yellow-300" },
{ token: "--icon-primary-secondary-disabled", value: "#fff08f", reference: "--yellow-200" },
{ token: "--icon-primary-inverse", value: "#fff8cc", reference: "--yellow-50" },
{ token: "--icon-primary-inverse-hover", value: "#fff5b8", reference: "--yellow-100" },
{ token: "--icon-primary-inverse-pressed", value: "#fff08f", reference: "--yellow-200" },
{ token: "--icon-primary-inverse-disabled", value: "#fffef5", reference: "--yellow-25" },
{ token: "--icon-primary-inverse-light", value: "#fff08f", reference: "--yellow-200" },
{ token: "--icon-primary-inverse-light-hover", value: "#ffe752", reference: "--yellow-300" },
{ token: "--icon-primary-inverse-light-pressed", value: "#ffe229", reference: "--yellow-400" },
{ token: "--icon-primary-inverse-light-disabled", value: "#fff08f", reference: "--yellow-200" },
{ token: "--icon-success-default", value: "#0a3312", reference: "--green-900" },
{ token: "--icon-success-default-hover", value: "#10501c", reference: "--green-800" },
{ token: "--icon-success-default-pressed", value: "#197b2b", reference: "--green-700" },
{ token: "--icon-success-default-disabled", value: "#1f9835", reference: "--green-600" },
{ token: "--icon-success-default-light", value: "#197b2b", reference: "--green-700" },
{ token: "--icon-success-default-light-hover", value: "#1f9835", reference: "--green-600" },
{ token: "--icon-success-default-light-pressed", value: "#25b53f", reference: "--green-500" },
{ token: "--icon-success-default-light-disabled", value: "#48c15e", reference: "--green-400" },
{ token: "--icon-success-secondary", value: "#25b53f", reference: "--green-500" },
{ token: "--icon-success-secondary-hover", value: "#48c15e", reference: "--green-400" },
{ token: "--icon-success-secondary-pressed", value: "#6bcd7c", reference: "--green-300" },
{ token: "--icon-success-secondary-disabled", value: "#9fdeab", reference: "--green-200" },
{ token: "--icon-success-inverse", value: "#d3f0d9", reference: "--green-50" },
{ token: "--icon-success-inverse-hover", value: "#c2eac9", reference: "--green-100" },
{ token: "--icon-success-inverse-pressed", value: "#9fdeab", reference: "--green-200" },
{ token: "--icon-success-inverse-disabled", value: "#d3f0d9", reference: "--green-50" },
{ token: "--icon-success-inverse-light", value: "#9fdeab", reference: "--green-200" },
{ token: "--icon-success-inverse-light-hover", value: "#6bcd7c", reference: "--green-300" },
{ token: "--icon-success-inverse-light-pressed", value: "#48c15e", reference: "--green-400" },
{ token: "--icon-success-inverse-light-disabled", value: "#9fdeab", reference: "--green-200" },
{ token: "--icon-error-default", value: "#3f0016", reference: "--red-900" },
{ token: "--icon-error-default-hover", value: "#630022", reference: "--red-800" },
{ token: "--icon-error-default-pressed", value: "#980034", reference: "--red-700" },
{ token: "--icon-error-default-disabled", value: "#bc0041", reference: "--red-600" },
{ token: "--icon-error-default-light", value: "#980034", reference: "--red-700" },
{ token: "--icon-error-default-light-hover", value: "#bc0041", reference: "--red-600" },
{ token: "--icon-error-default-light-pressed", value: "#e0004d", reference: "--red-500" },
{ token: "--icon-error-default-light-disabled", value: "#e52969", reference: "--red-400" },
{ token: "--icon-error-secondary", value: "#e0004d", reference: "--red-500" },
{ token: "--icon-error-secondary-hover", value: "#e52969", reference: "--red-400" },
{ token: "--icon-error-secondary-pressed", value: "#ea5286", reference: "--red-300" },
{ token: "--icon-error-secondary-disabled", value: "#f18fb1", reference: "--red-200" },
{ token: "--icon-error-inverse", value: "#f9ccdb", reference: "--red-50" },
{ token: "--icon-error-inverse-hover", value: "#f6b8cd", reference: "--red-100" },
{ token: "--icon-error-inverse-pressed", value: "#f18fb1", reference: "--red-200" },
{ token: "--icon-error-inverse-disabled", value: "#f9ccdb", reference: "--red-50" },
{ token: "--icon-error-inverse-light", value: "#f18fb1", reference: "--red-200" },
{ token: "--icon-error-inverse-light-hover", value: "#ea5286", reference: "--red-300" },
{ token: "--icon-error-inverse-light-pressed", value: "#e52969", reference: "--red-400" },
{ token: "--icon-error-inverse-light-disabled", value: "#f18fb1", reference: "--red-200" },
{ token: "--icon-accent-default", value: "#130531", reference: "--purple-900" },
{ token: "--icon-accent-default-hover", value: "#1d084d", reference: "--purple-800" },
{ token: "--icon-accent-default-pressed", value: "#2e0c76", reference: "--purple-700" },
{ token: "--icon-accent-default-disabled", value: "#380f92", reference: "--purple-600" },
{ token: "--icon-accent-default-light", value: "#2e0c76", reference: "--purple-700" },
{ token: "--icon-accent-default-light-hover", value: "#380f92", reference: "--purple-600" },
{ token: "--icon-accent-default-light-pressed", value: "#4312ae", reference: "--purple-500" },
{ token: "--icon-accent-default-light-disabled", value: "#6138bb", reference: "--purple-400" },
{ token: "--icon-accent-secondary", value: "#4312ae", reference: "--purple-500" },
{ token: "--icon-accent-secondary-hover", value: "#6138bb", reference: "--purple-400" },
{ token: "--icon-accent-secondary-pressed", value: "#7f5ec8", reference: "--purple-300" },
{ token: "--icon-accent-secondary-disabled", value: "#ac97db", reference: "--purple-200" },
{ token: "--icon-accent-inverse", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--icon-accent-inverse-hover", value: "#cabde8", reference: "--purple-100" },
{ token: "--icon-accent-inverse-pressed", value: "#ac97db", reference: "--purple-200" },
{ token: "--icon-accent-inverse-disabled", value: "#d9d0ef", reference: "--purple-50" },
{ token: "--icon-accent-inverse-light", value: "#ac97db", reference: "--purple-200" },
{ token: "--icon-accent-inverse-light-hover", value: "#7f5ec8", reference: "--purple-300" },
{ token: "--icon-accent-inverse-light-pressed", value: "#6138bb", reference: "--purple-400" },
{ token: "--icon-accent-inverse-light-disabled", value: "#ac97db", reference: "--purple-200" },
{ token: "--icon-warning-default", value: "#461d00", reference: "--orange-900" },
{ token: "--icon-warning-default-hover", value: "#6e2e00", reference: "--orange-800" },
{ token: "--icon-warning-default-pressed", value: "#aa4700", reference: "--orange-700" },
{ token: "--icon-warning-default-disabled", value: "#d25800", reference: "--orange-600" },
{ token: "--icon-warning-default-light", value: "#aa4700", reference: "--orange-700" },
{ token: "--icon-warning-default-light-hover", value: "#d25800", reference: "--orange-600" },
{ token: "--icon-warning-default-light-pressed", value: "#fa6900", reference: "--orange-500" },
{ token: "--icon-warning-default-light-disabled", value: "#fb8129", reference: "--orange-400" },
{ token: "--icon-warning-secondary", value: "#fa6900", reference: "--orange-500" },
{ token: "--icon-warning-secondary-hover", value: "#fb8129", reference: "--orange-400" },
{ token: "--icon-warning-secondary-pressed", value: "#fc9952", reference: "--orange-300" },
{ token: "--icon-warning-secondary-disabled", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--icon-warning-inverse", value: "#fee1cc", reference: "--orange-50" },
{ token: "--icon-warning-inverse-hover", value: "#fed5b8", reference: "--orange-100" },
{ token: "--icon-warning-inverse-pressed", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--icon-warning-inverse-disabled", value: "#fee1cc", reference: "--orange-50" },
{ token: "--icon-warning-inverse-light", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--icon-warning-inverse-light-hover", value: "#fc9952", reference: "--orange-300" },
{ token: "--icon-warning-inverse-light-pressed", value: "#fb8129", reference: "--orange-400" },
{ token: "--icon-warning-inverse-light-disabled", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--border-base-default-hover", value: "#25272c", reference: "--neutral-800" },
{ token: "--border-base-secondary-hover", value: "#555963", reference: "--neutral-500" },
{ token: "--border-base-secondary-focused", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--border-base-secondary-pressed", value: "#474b53", reference: "--neutral-600" },
{ token: "--border-base-secondary-disabled", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--border-base-default-focused", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--border-base-default-pressed", value: "#18191c", reference: "--neutral-900" },
{ token: "--border-base-default-disabled", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--border-base-default", value: "#70747c", reference: "--neutral-400" },
{ token: "--border-base-secondary", value: "#cfd1d3", reference: "--neutral-100" },
{ token: "--border-base-tertiary", value: "#dddee0", reference: "--neutral-50" },
{ token: "--border-base-light", value: "#55596314", reference: "--neutral-transparent-08" },
{ token: "--border-base-inverse", value: "#25272c", reference: "--neutral-800" },
{ token: "--border-base-tertiary-hover", value: "#70747c", reference: "--neutral-400" },
{ token: "--border-base-light-hover", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--border-base-light-focused", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--border-base-light-pressed", value: "#5559633d", reference: "--neutral-transparent-24" },
{ token: "--border-base-light-disabled", value: "#55596314", reference: "--neutral-transparent-08" },
{ token: "--border-base-tertiary-focused", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--border-base-tertiary-pressed", value: "#555963", reference: "--neutral-500" },
{ token: "--border-base-tertiary-disabled", value: "#dddee0", reference: "--neutral-50" },
{ token: "--border-base-inverse-hover", value: "#3a3d43", reference: "--neutral-700" },
{ token: "--border-base-inverse-focused", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--border-base-inverse-pressed", value: "#474b53", reference: "--neutral-600" },
{ token: "--border-base-inverse-disabled", value: "#70747c", reference: "--neutral-400" },
{ token: "--border-primary-default", value: "#ffdc00", reference: "--yellow-500" },
{ token: "--border-primary-hover", value: "#706100", reference: "--yellow-800" },
{ token: "--border-primary-focused", value: "#ffdc0029", reference: "--yellow-transparent-16" },
{ token: "--border-primary-pressed", value: "#473e00", reference: "--yellow-900" },
{ token: "--border-primary-disabled", value: "#fff08f", reference: "--yellow-200" },
{ token: "--border-success-default", value: "#25b53f", reference: "--green-500" },
{ token: "--border-success-hover", value: "#10501c", reference: "--green-800" },
{ token: "--border-success-focused", value: "#25b53f29", reference: "--green-transparent-16" },
{ token: "--border-success-pressed", value: "#0a3312", reference: "--green-900" },
{ token: "--border-success-disabled", value: "#9fdeab", reference: "--green-200" },
{ token: "--border-error-default", value: "#e0004d", reference: "--red-500" },
{ token: "--border-error-hover", value: "#630022", reference: "--red-800" },
{ token: "--border-error-focused", value: "#e0004d29", reference: "--red-transparent-16" },
{ token: "--border-error-pressed", value: "#3f0016", reference: "--red-900" },
{ token: "--border-error-disabled", value: "#f18fb1", reference: "--red-200" },
{ token: "--border-accent-default", value: "#4312ae", reference: "--purple-500" },
{ token: "--border-accent-hover", value: "#1d084d", reference: "--purple-800" },
{ token: "--border-accent-focused", value: "#4312ae29", reference: "--purple-transparent-16" },
{ token: "--border-accent-pressed", value: "#130531", reference: "--purple-900" },
{ token: "--border-accent-disabled", value: "#ac97db", reference: "--purple-200" },
{ token: "--border-warning-default", value: "#fa6900", reference: "--orange-500" },
{ token: "--border-warning-hover", value: "#6e2e00", reference: "--orange-800" },
{ token: "--border-warning-focused", value: "#fa690029", reference: "--orange-transparent-16" },
{ token: "--border-warning-pressed", value: "#461d00", reference: "--orange-900" },
{ token: "--border-warning-disabled", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--border-white-default", value: "#ffffff7a", reference: "--white-500-48" },
{ token: "--border-white-hover", value: "#ffffffcc", reference: "--white-900-80" },
{ token: "--border-white-focused", value: "#ffffff29", reference: "--white-100-16" },
{ token: "--border-white-pressed", value: "#ffffffcc", reference: "--white-900-80" },
{ token: "--border-white-disabled", value: "#ffffff3d", reference: "--white-200-24" },
{ token: "--border-white-full", value: "#ffffff", reference: "--white-1000" },
{ token: "--border-black-default", value: "#0000007a", reference: "--black-500-48" },
{ token: "--border-black-hover", value: "#000000cc", reference: "--black-900-80" },
{ token: "--border-black-focused", value: "#00000029", reference: "--black-100-16" },
{ token: "--border-black-pressed", value: "#000000cc", reference: "--black-900-80" },
{ token: "--border-black-disabled", value: "#0000003d", reference: "--black-200-24" },
{ token: "--transparent-background-base-hover", value: "#55596314", reference: "--neutral-transparent-08" },
{ token: "--transparent-background-base-focused", value: "#55596329", reference: "--neutral-transparent-16" },
{ token: "--transparent-background-base-pressed", value: "#5559633d", reference: "--neutral-transparent-24" },
{ token: "--transparent-background-primary-hover", value: "#ffdc0014", reference: "--yellow-transparent-08" },
{ token: "--transparent-background-primary-focused", value: "#ffdc0029", reference: "--yellow-transparent-16" },
{ token: "--transparent-background-primary-pressed", value: "#ffdc003d", reference: "--yellow-transparent-24" },
{ token: "--transparent-background-success-hover", value: "#25b53f14", reference: "--green-transparent-08" },
{ token: "--transparent-background-error-hover", value: "#e0004d14", reference: "--red-transparent-08" },
{ token: "--transparent-background-accent-hover", value: "#4312ae14", reference: "--purple-transparent-08" },
{ token: "--transparent-background-warning-hover", value: "#fa690014", reference: "--orange-transparent-08" },
{ token: "--transparent-background-white-hover", value: "#ffffff14", reference: "--white-50-08" },
{ token: "--transparent-background-black-hover", value: "#00000014", reference: "--black-50-08" },
{ token: "--transparent-background-black-focused", value: "#00000029", reference: "--black-100-16" },
{ token: "--transparent-background-black-pressed", value: "#0000003d", reference: "--black-200-24" },
{ token: "--transparent-background-black-scrim", value: "#000000cc", reference: "--black-900-80" },
{ token: "--transparent-background-white-focused", value: "#ffffff29", reference: "--white-100-16" },
{ token: "--transparent-background-white-pressed", value: "#ffffff3d", reference: "--white-200-24" },
{ token: "--transparent-background-warning-focused", value: "#fa690029", reference: "--orange-transparent-16" },
{ token: "--transparent-background-warning-pressed", value: "#fa69003d", reference: "--orange-transparent-24" },
{ token: "--transparent-background-accent-focused", value: "#4312ae29", reference: "--purple-transparent-16" },
{ token: "--transparent-background-accent-pressed", value: "#4312ae3d", reference: "--purple-transparent-24" },
{ token: "--transparent-background-error-focused", value: "#e0004d29", reference: "--red-transparent-16" },
{ token: "--transparent-background-error-pressed", value: "#e0004d3d", reference: "--red-transparent-24" },
{ token: "--transparent-background-success-focused", value: "#25b53f29", reference: "--green-transparent-16" },
{ token: "--transparent-background-success-pressed", value: "#25b53f3d", reference: "--green-transparent-24" },
{ token: "--transparent-text-default", value: "#000000cc", reference: "--black-900-80" },
{ token: "--transparent-text-default-hover", value: "#000000b8", reference: "--black-800-72" },
{ token: "--transparent-text-default-pressed", value: "#000000a3", reference: "--black-700-64" },
{ token: "--transparent-text-default-disabled", value: "#0000008f", reference: "--black-600-56" },
{ token: "--transparent-text-default-light", value: "#000000a3", reference: "--black-700-64" },
{ token: "--transparent-text-default-light-hover", value: "#0000008f", reference: "--black-600-56" },
{ token: "--transparent-text-default-light-pressed", value: "#0000007a", reference: "--black-500-48" },
{ token: "--transparent-text-default-light-disabled", value: "#00000066", reference: "--black-400-40" },
{ token: "--transparent-text-secondary", value: "#0000007a", reference: "--black-500-48" },
{ token: "--transparent-text-secondary-hover", value: "#00000066", reference: "--black-400-40" },
{ token: "--transparent-text-secondary-pressed", value: "#00000052", reference: "--black-300-32" },
{ token: "--transparent-text-secondary-disabled", value: "#0000003d", reference: "--black-200-24" },
{ token: "--transparent-text-inverse", value: "#ffffff14", reference: "--white-50-08" },
{ token: "--transparent-text-inverse-hover", value: "#ffffff29", reference: "--white-100-16" },
{ token: "--transparent-text-inverse-pressed", value: "#ffffff3d", reference: "--white-200-24" },
{ token: "--transparent-text-inverse-disabled", value: "#ffffff7a", reference: "--white-500-48" },
{ token: "--transparent-text-inverse-light", value: "#ffffff3d", reference: "--white-200-24" },
{ token: "--transparent-text-inverse-light-hover", value: "#ffffff52", reference: "--white-300-32" },
{ token: "--transparent-text-inverse-light-pressed", value: "#ffffff66", reference: "--white-400-40" },
{ token: "--transparent-text-inverse-light-disabled", value: "#ffffffa3", reference: "--white-700-64" },
{ token: "--transparent-icon-default", value: "#000000cc", reference: "--black-900-80" },
{ token: "--transparent-icon-default-hover", value: "#000000b8", reference: "--black-800-72" },
{ token: "--transparent-icon-default-pressed", value: "#000000a3", reference: "--black-700-64" },
{ token: "--transparent-icon-default-disabled", value: "#0000008f", reference: "--black-600-56" },
{ token: "--transparent-icon-default-light", value: "#000000a3", reference: "--black-700-64" },
{ token: "--transparent-icon-default-light-hover", value: "#0000008f", reference: "--black-600-56" },
{ token: "--transparent-icon-default-light-pressed", value: "#0000007a", reference: "--black-500-48" },
{ token: "--transparent-icon-default-light-disabled", value: "#00000066", reference: "--black-400-40" },
{ token: "--transparent-icon-secondary", value: "#0000007a", reference: "--black-500-48" },
{ token: "--transparent-icon-secondary-hover", value: "#00000066", reference: "--black-400-40" },
{ token: "--transparent-icon-secondary-pressed", value: "#00000052", reference: "--black-300-32" },
{ token: "--transparent-icon-secondary-disabled", value: "#0000003d", reference: "--black-200-24" },
{ token: "--transparent-icon-inverse", value: "#ffffff14", reference: "--white-50-08" },
{ token: "--transparent-icon-inverse-hover", value: "#ffffff29", reference: "--white-100-16" },
{ token: "--transparent-icon-inverse-pressed", value: "#ffffff3d", reference: "--white-200-24" },
{ token: "--transparent-icon-inverse-disabled", value: "#ffffff7a", reference: "--white-500-48" },
{ token: "--transparent-icon-inverse-light", value: "#ffffff3d", reference: "--white-200-24" },
{ token: "--transparent-icon-inverse-light-hover", value: "#ffffff52", reference: "--white-300-32" },
{ token: "--transparent-icon-inverse-light-pressed", value: "#ffffff66", reference: "--white-400-40" },
{ token: "--transparent-icon-inverse-light-disabled", value: "#ffffffa3", reference: "--white-700-64" },
{ token: "--text-warning-default", value: "#461d00", reference: "--orange-900" },
{ token: "--text-warning-default-hover", value: "#6e2e00", reference: "--orange-800" },
{ token: "--text-warning-default-pressed", value: "#aa4700", reference: "--orange-700" },
{ token: "--text-warning-default-disabled", value: "#d25800", reference: "--orange-600" },
{ token: "--text-warning-default-light", value: "#aa4700", reference: "--orange-700" },
{ token: "--text-warning-default-light-hover", value: "#d25800", reference: "--orange-600" },
{ token: "--text-warning-default-light-pressed", value: "#fa6900", reference: "--orange-500" },
{ token: "--text-warning-default-light-disabled", value: "#fb8129", reference: "--orange-400" },
{ token: "--text-warning-secondary", value: "#fa6900", reference: "--orange-500" },
{ token: "--text-warning-secondary-hover", value: "#fb8129", reference: "--orange-400" },
{ token: "--text-warning-secondary-pressed", value: "#fc9952", reference: "--orange-300" },
{ token: "--text-warning-secondary-disabled", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--text-warning-inverse", value: "#fee1cc", reference: "--orange-50" },
{ token: "--text-warning-inverse-hover", value: "#fed5b8", reference: "--orange-100" },
{ token: "--text-warning-inverse-pressed", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--text-warning-inverse-disabled", value: "#fee1cc", reference: "--orange-50" },
{ token: "--text-warning-inverse-light", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--text-warning-inverse-light-hover", value: "#fc9952", reference: "--orange-300" },
{ token: "--text-warning-inverse-light-pressed", value: "#fb8129", reference: "--orange-400" },
{ token: "--text-warning-inverse-light-disabled", value: "#fdbd8f", reference: "--orange-200" },
{ token: "--background-base-inverse-light-hover", value: "#555963", reference: "--neutral-500" },
{ token: "--background-base-inverse-light-pressed", value: "#70747c", reference: "--neutral-400" },
{ token: "--background-base-inverse-light-disabled", value: "#b4b6ba", reference: "--neutral-200" }
] as const;

export const spacingTokens = [
  { token: "--space-0", value: 0 },
  { token: "--space-1", value: 1 },
  { token: "--space-2", value: 2 },
  { token: "--space-4", value: 4 },
  { token: "--space-6", value: 6 },
  { token: "--space-8", value: 8 },
  { token: "--space-10", value: 10 },
  { token: "--space-12", value: 12 },
  { token: "--space-16", value: 16 },
  { token: "--space-20", value: 20 },
  { token: "--space-24", value: 24 },
  { token: "--space-32", value: 32 },
  { token: "--space-40", value: 40 },
  { token: "--space-48", value: 48 }
] as const;

export const radiusTokens = [
  { token: "--radius-no", value: 0 },
  { token: "--radius-smallest", value: 2 },
  { token: "--radius-small", value: 4 },
  { token: "--radius-middle", value: 8 },
  { token: "--radius-large", value: 16 },
  { token: "--radius-full", value: 9999 }
] as const;

export const depthTokens = [
  { token: "--depth-n4", value: -4 },
  { token: "--depth-n2", value: -2 },
  { token: "--depth-n1", value: -1 },
  { token: "--depth-0", value: 0 },
  { token: "--depth-1", value: 1 },
  { token: "--depth-2", value: 2 },
  { token: "--depth-4", value: 4 },
  { token: "--depth-8", value: 8 },
  { token: "--depth-12", value: 12 },
  { token: "--depth-16", value: 16 }
] as const;

export const elementTokens = [
  { token: "--elements-4", value: 4 },
  { token: "--elements-8", value: 8 },
  { token: "--elements-12", value: 12 },
  { token: "--elements-16", value: 16 },
  { token: "--elements-20", value: 20 },
  { token: "--elements-24", value: 24 },
  { token: "--elements-28", value: 28 },
  { token: "--elements-32", value: 32 },
  { token: "--elements-40", value: 40 },
  { token: "--elements-48", value: 48 },
  { token: "--elements-56", value: 56 },
  { token: "--elements-64", value: 64 },
  { token: "--elements-72", value: 72 }
] as const;

export const borderTokens = [
  { token: "--border-small", value: 1 },
  { token: "--border-middle", value: 2 },
  { token: "--border-large", value: 4 }
] as const;

export const responsiveTokens = [
  { token: "--platform-desktop", value: 1280 },
  { token: "--platform-tablet", value: 768 },
  { token: "--platform-mobile", value: 320 },
  { token: "--platform-desktop-full", value: 1920 }
] as const;

export const typographyPrimitiveTokens = [
  { token: "--font-family-title", value: "TT Commons Pro Expanded" },
  { token: "--font-family-sans", value: "Inter" },
  { token: "--font-family-mono", value: "Roboto Mono" },
  { token: "--font-weight-regular", value: "400" },
  { token: "--font-style-regular-italic", value: "Italic" },
  { token: "--font-style-semibold-italic", value: "Semi Bold Italic" },
  { token: "--font-style-demibold-italic", value: "DemiBold Italic" },
  { token: "--font-style-extrabold-italic", value: "ExtraBold Italic" },
  { token: "--font-weight-semibold", value: "600" },
  { token: "--font-weight-bold", value: "700" },
  { token: "--font-size-9", value: 9 },
  { token: "--font-weight-extrabold", value: "800" },
  { token: "--font-size-10", value: 10 },
  { token: "--font-size-12", value: 12 },
  { token: "--font-size-14", value: 14 },
  { token: "--font-size-16", value: 16 },
  { token: "--font-size-20", value: 20 },
  { token: "--font-size-24", value: 24 },
  { token: "--font-size-32", value: 32 },
  { token: "--font-size-40", value: 40 },
  { token: "--line-height-12", value: 12 },
  { token: "--line-height-14", value: 14 },
  { token: "--line-height-16", value: 16 },
  { token: "--line-height-20", value: 20 },
  { token: "--line-height-24", value: 24 },
  { token: "--line-height-28", value: 28 },
  { token: "--line-height-32", value: 32 },
  { token: "--line-height-40", value: 40 },
  { token: "--line-height-48", value: 48 },
  { token: "--text-decoration-none", value: "None" },
  { token: "--text-decoration-underline", value: "Underline" },
  { token: "--text-decoration-underline-dashed", value: "Underline dashed" }
] as const;

export const typographyTokens = [
  {
    "name": "H0 Heading",
    "token": "--h0-heading",
    "family": "TT Commons Pro Expanded",
    "weight": 800,
    "size": 40,
    "lineHeight": 48,
    "mobileSize": 32,
    "mobileLineHeight": 40,
    "references": {
      "family": "var(--font-family-title)",
      "weight": "var(--font-weight-extrabold)",
      "size": "var(--font-size-40)",
      "lineHeight": "var(--line-height-48)",
      "mobileSize": "var(--font-size-32)",
      "mobileLineHeight": "var(--line-height-40)",
      "style": null
    }
  },
  {
    "name": "H1 Heading",
    "token": "--h1-heading",
    "family": "TT Commons Pro Expanded",
    "weight": 800,
    "size": 32,
    "lineHeight": 40,
    "mobileSize": 24,
    "mobileLineHeight": 32,
    "references": {
      "family": "var(--font-family-title)",
      "weight": "var(--font-weight-extrabold)",
      "size": "var(--font-size-32)",
      "lineHeight": "var(--line-height-40)",
      "mobileSize": "var(--font-size-24)",
      "mobileLineHeight": "var(--line-height-32)",
      "style": null
    }
  },
  {
    "name": "H2 Heading",
    "token": "--h2-heading",
    "family": "TT Commons Pro Expanded",
    "weight": 800,
    "size": 24,
    "lineHeight": 32,
    "mobileSize": 20,
    "mobileLineHeight": 28,
    "references": {
      "family": "var(--font-family-title)",
      "weight": "var(--font-weight-extrabold)",
      "size": "var(--font-size-24)",
      "lineHeight": "var(--line-height-32)",
      "mobileSize": "var(--font-size-20)",
      "mobileLineHeight": "var(--line-height-28)",
      "style": null
    }
  },
  {
    "name": "H3 Heading",
    "token": "--h3-heading",
    "family": "TT Commons Pro Expanded",
    "weight": 800,
    "size": 20,
    "lineHeight": 28,
    "mobileSize": 16,
    "mobileLineHeight": 24,
    "references": {
      "family": "var(--font-family-title)",
      "weight": "var(--font-weight-extrabold)",
      "size": "var(--font-size-20)",
      "lineHeight": "var(--line-height-28)",
      "mobileSize": "var(--font-size-16)",
      "mobileLineHeight": "var(--line-height-24)",
      "style": null
    }
  },
  {
    "name": "Subtitle,
    "token": "--subtitle",
    "family": "Inter",
    "weight": 400,
    "size": 16,
    "lineHeight": 24,
    "mobileSize": 14,
    "mobileLineHeight": 20,
    "references": {
      "family": "var(--font-family-sans)",
      "weight": "var(--font-weight-regular)",
      "size": "var(--font-size-16)",
      "lineHeight": "var(--line-height-24)",
      "mobileSize": "var(--font-size-14)",
      "mobileLineHeight": "var(--line-height-20)",
      "style": null
    }
  },
  {
    "name": "Body,
    "token": "--body",
    "family": "Inter",
    "weight": 400,
    "size": 14,
    "lineHeight": 20,
    "mobileSize": 12,
    "mobileLineHeight": 16,
    "references": {
      "family": "var(--font-family-sans)",
      "weight": "var(--font-weight-regular)",
      "size": "var(--font-size-14)",
      "lineHeight": "var(--line-height-20)",
      "mobileSize": "var(--font-size-12)",
      "mobileLineHeight": "var(--line-height-16)",
      "style": "var(--font-style-regular-italic)"
    }
  },
  {
    "name": "Caption,
    "token": "--caption",
    "family": "Inter",
    "weight": 400,
    "size": 12,
    "lineHeight": 16,
    "mobileSize": 10,
    "mobileLineHeight": 14,
    "references": {
      "family": "var(--font-family-sans)",
      "weight": "var(--font-weight-regular)",
      "size": "var(--font-size-12)",
      "lineHeight": "var(--line-height-16)",
      "mobileSize": "var(--font-size-10)",
      "mobileLineHeight": "var(--line-height-14)",
      "style": null
    }
  },
  {
    "name": "Overline,
    "token": "--overline",
    "family": "Inter",
    "weight": 400,
    "size": 10,
    "lineHeight": 14,
    "mobileSize": 9,
    "mobileLineHeight": 12,
    "references": {
      "family": "var(--font-family-sans)",
      "weight": "var(--font-weight-regular)",
      "size": "var(--font-size-10)",
      "lineHeight": "var(--line-height-14)",
      "mobileSize": "var(--font-size-9)",
      "mobileLineHeight": "var(--line-height-12)",
      "style": null
    }
  },
  {
    "name": "Code,
    "token": "--code",
    "family": "Roboto Mono",
    "weight": 400,
    "size": 14,
    "lineHeight": 20,
    "mobileSize": 12,
    "mobileLineHeight": 16,
    "references": {
      "family": "var(--font-family-mono)",
      "weight": "var(--font-weight-regular)",
      "size": "var(--font-size-14)",
      "lineHeight": "var(--line-height-20)",
      "mobileSize": "var(--font-size-12)",
      "mobileLineHeight": "var(--line-height-16)",
      "style": null
    }
  }
] as const;

export const effectTokens = [
  { token: "--drop-shadow-shadow-xs", value: "0px 1px 4px 0px #0000000a" },
  { token: "--drop-shadow-shadow-xs-hover", value: "0px 1px 4px 0px #0000000a, 0px 2px 4px 0px #00000014" },
  { token: "--drop-shadow-shadow-s", value: "0px 1px 8px -1px #00000014" },
  { token: "--drop-shadow-shadow-s-hover", value: "0px 1px 8px -1px #00000014, 0px 2px 4px 0px #00000014" },
  { token: "--drop-shadow-shadow-m", value: "0px 1px 12px -2px #00000029" },
  { token: "--drop-shadow-shadow-m-hover", value: "0px 1px 12px -2px #00000029, 0px 2px 4px 0px #00000014" },
  { token: "--drop-shadow-shadow-l", value: "0px 1px 16px -4px #0000003d" },
  { token: "--drop-shadow-shadow-l-hover", value: "0px 1px 16px -4px #0000003d, 0px 2px 4px 0px #00000014" }
] as const;
