import type { Meta, StoryObj } from '@storybook/react-vite';
import { Select } from './Select';
import { selectionDocs } from '../../docs/selection-components';
const options=[{value:'draft',label:'Черновик',description:'Документ еще не отправлен'},{value:'sent',label:'Отправлен',description:'Ожидает подписи'},{value:'blocked',label:'Архив',disabled:true},{value:'signed',label:'Подписан',helper:'Готово'}];
const meta={title:'Components/Selection/Select',component:Select,tags:['autodocs','ready'],parameters:{layout:'padded',docs:{description:{component:selectionDocs('Select')}}},args:{label:'Статус документа',placeholder:'Выберите статус',options,caption:'Текущее состояние документа'},decorators:[Story=><div style={{width:'100%',maxWidth:456}}><Story/></div>],argTypes:{size:{control:'radio',options:['small','medium']},creatable:{control:'boolean'},clearable:{control:'boolean'},disabled:{control:'boolean'},skeleton:{control:'boolean'},placement:{control:'select',options:['auto','top','bottom']}}} satisfies Meta<typeof Select>;
export default meta;type Story=StoryObj<typeof meta>;
export const Default:Story={};
export const Sizes:Story={name:'Размеры',render:args=><div style={{display:'grid',gap:24}}><Select {...args} size="medium"/><Select {...args} size="small"/></div>};
export const States:Story={name:'Состояния',render:args=><div style={{display:'grid',gap:24}}><Select {...args}/><Select {...args} defaultValue="draft" clearable/><Select {...args} error="Выберите статус" required/><Select {...args} disabled defaultValue="sent"/><Select {...args} disabled error="Выбор недоступен"/><Select {...args} skeleton/></div>};
export const Creatable:Story={name:'Собственное значение',args:{creatable:true,clearable:true,label:'Категория',placeholder:'Выберите или введите категорию',caption:'Enter сохраняет новое значение. Список вариантов не фильтруется'}};
export const WithDescription:Story={name:'Полный состав',args:{defaultValue:'signed',description:'Дополнительное описание',leadingIcon:'copy',counter:'1 / 1',required:true,clearable:true}};
export const Skeleton:Story={args:{skeleton:true,description:'Описание',leadingIcon:'copy',counter:'1 / 1'}};
export const Empty:Story={name:'Пустой список',args:{options:[]}};
export const LongList:Story={name:'Длинный список',args:{options:Array.from({length:100},(_,i)=>({value:String(i+1),label:`Организация ${i+1}`}))}};
export const AtEdge:Story={name:'Раскрытие вверх',decorators:[Story=><div style={{height:'calc(100vh - 48px)',display:'flex',alignItems:'flex-end'}}><Story/></div>]};
