import type { Meta, StoryObj } from '@storybook/react-vite';
import { CheckboxGroup } from './SelectionGroup';
import { componentDocs } from '../../docs/bulk-components';
import { qualityDocs } from '../../docs/quality';
const meta={title:'Components/Selection/CheckboxGroup',component:CheckboxGroup,tags:['autodocs','ready'],parameters:{layout:'padded',docs:{description:{component:componentDocs('CheckboxGroup')+qualityDocs('CheckboxGroup')}}},args:{label:'Уведомления',description:'Выберите способ получения',defaultValue:['email'],options:[{value:'email',label:'Электронная почта',description:'На рабочий адрес'},{value:'sms',label:'Сообщения на телефон'},{value:'push',label:'Push-уведомления',disabled:true}]},argTypes:{options:{control:'object'},direction:{control:'radio',options:['column','row']},position:{control:'radio',options:['top','left']},disabled:{control:'boolean'},state:{control:'select',options:['default','disabled','skeleton']},onValueChange:{action:'valueChange'}}} satisfies Meta<typeof CheckboxGroup>;
export default meta;type Story=StoryObj<typeof meta>;
export const Default:Story={};
export const Horizontal:Story={args:{direction:'row'}};
export const Disabled:Story={args:{disabled:true}};
export const Error:Story={args:{errorText:'Выберите хотя бы один способ'}};
export const Skeleton:Story={args:{state:'skeleton'}};
export const LabelLeft:Story={args:{position:'left'},decorators:[Story=><div style={{maxWidth:424}}><Story/></div>]};
