import { describe,it,expect,vi } from 'vitest';
import { render,screen,fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { axe } from 'jest-axe';
import { Checkbox,Radio,Switch } from './SelectionControl';
import { CheckboxGroup,RadioGroup,SwitchGroup } from './SelectionGroup';
const options=[{value:'a',label:'Почта'},{value:'b',label:'Телефон'},{value:'c',label:'Архив',disabled:true}];
describe('Selection controls',()=>{
 it('toggles checkbox from its label and Space, not Enter',async()=>{const user=userEvent.setup();render(<Checkbox label="Выбрать документ"/>);const box=screen.getByRole('checkbox');await user.click(screen.getByText('Выбрать документ'));expect(box).toBeChecked();await user.keyboard('{Enter}');expect(box).toBeChecked();await user.keyboard(' ');expect(box).not.toBeChecked();});
 it('sets native indeterminate and mixed aria state',()=>{const {rerender}=render(<Checkbox aria-label="Все" indeterminate/>);const box=screen.getByRole('checkbox') as HTMLInputElement;expect(box.indeterminate).toBe(true);expect(box).toHaveAttribute('aria-checked','mixed');rerender(<Checkbox aria-label="Все" indeterminate={false}/>);expect(box.indeterminate).toBe(false);expect(box).not.toHaveAttribute('aria-checked');});
 it('supports native form data and reset',()=>{render(<form data-testid="form"><Checkbox label="Почта" name="channel" value="email" defaultChecked/></form>);const form=screen.getByTestId('form') as HTMLFormElement;expect(new FormData(form).get('channel')).toBe('email');fireEvent.click(screen.getByRole('checkbox'));expect(new FormData(form).get('channel')).toBe(null);form.reset();expect(screen.getByRole('checkbox')).toBeChecked();});
 it('switch responds to Enter and Space',async()=>{const user=userEvent.setup();render(<Switch label="Автосохранение"/>);await user.tab();await user.keyboard('{Enter}');expect(screen.getByRole('switch')).toBeChecked();await user.keyboard(' ');expect(screen.getByRole('switch')).not.toBeChecked();});
 it.each([Checkbox,Radio,Switch])('disabled and skeleton are not interactive',async Control=>{const user=userEvent.setup(),onChange=vi.fn();const {rerender}=render(<Control label="Опция" disabled onChange={onChange}/>);await user.click(screen.getByText('Опция'));await user.tab();expect(onChange).not.toHaveBeenCalled();expect(document.activeElement).toBe(document.body);rerender(<Control label="Опция" state="skeleton"/>);expect(document.querySelector('input')).toBe(null);});
 it('connects option error instead of description',()=>{render(<Checkbox label="Опция" description="Описание" errorText="Ошибка"/>);expect(screen.queryByText('Описание')).toBe(null);expect(screen.getByRole('checkbox')).toHaveAccessibleDescription('Ошибка');expect(screen.getByRole('checkbox')).toHaveAttribute('aria-invalid','true');});
 it('radio group enforces one selection',async()=>{const user=userEvent.setup();render(<RadioGroup label="Способ" options={options} defaultValue="a"/>);await user.click(screen.getByLabelText('Телефон'));expect(screen.getByLabelText('Телефон')).toBeChecked();expect(screen.getByLabelText('Почта')).not.toBeChecked();});
 it.each([CheckboxGroup,SwitchGroup])('group keeps independent selected values',async Group=>{const user=userEvent.setup(),change=vi.fn();render(<Group label="Способы" options={options} defaultValue={['a']} onValueChange={change}/>);await user.click(screen.getByText('Телефон'));expect(change).toHaveBeenLastCalledWith(['a','b']);await user.click(screen.getByText('Почта'));expect(change).toHaveBeenLastCalledWith(['b']);});
 it('controlled group waits for updated props',async()=>{const user=userEvent.setup(),change=vi.fn();render(<CheckboxGroup label="Способы" options={options} value={['a']} onValueChange={change}/>);await user.click(screen.getByText('Телефон'));expect(change).toHaveBeenCalledWith(['a','b']);expect(screen.getByLabelText('Телефон')).not.toBeChecked();});
 it('has accessible groups and individual error descriptions',async()=>{const {container}=render(<><RadioGroup label="Способ" description="Один вариант" errorText="Нужно выбрать" options={options}/><Checkbox label="Условия" errorText="Примите условия"/><Switch label="Сохранять"/></>);expect((await axe(container)).violations).toEqual([]);});
});
