import { expect,test,type Locator } from '@playwright/test';
async function token(el:Locator,property:string,name:string){return el.evaluate((node,{property,name})=>{const probe=document.createElement('span');probe.style.setProperty(property,`var(${name})`);node.appendChild(probe);const value=getComputedStyle(probe).getPropertyValue(property);probe.remove();return value;},{property,name});}
for(const kind of ['checkbox','radio','switch']) {
 test(`${kind} state geometry and token matrix`,async({page})=>{
  await page.goto(`/iframe.html?id=components-selection-${kind}--states&viewMode=story`);
  const all=page.locator('.fdoc-control');await expect(all).toHaveCount(24);
  for(let row=0;row<4;row++)for(let col=0;col<6;col++){
   const control=all.nth(row*6+col);await expect(control).toHaveCSS('width',kind==='switch'?'36px':'24px');await expect(control).toHaveCSS('height',kind==='switch'?'20px':'24px');
   if(col===5){await expect(control.locator('input')).toHaveCount(0);continue;}
   const shape=control.locator('.fdoc-control__shape');await expect(shape).toHaveCSS('width',kind==='switch'?'36px':'20px');await expect(shape).toHaveCSS('height','20px');
   const checked=row%2===1,error=row>=2&&kind!=='switch',suffix=col===4?'-disabled':'';
   if(checked||kind==='switch')await expect(shape).toHaveCSS('background-color',await token(control,'background-color',`--background-${error?'error-default':checked?'primary-default':'base-tertiary'}${suffix}`));
   if([1,2,3].includes(col)){const layer=control.locator('.fdoc-control__ripple');await expect(layer).toHaveCSS('width','32px');await expect(layer).toHaveCSS('background-color',await token(control,'background-color',`--transparent-background-${error?'error':checked?'primary':'base'}-${['','hover','focused','pressed'][col]}`));}
   if(col===4)await expect(control.locator('input')).toBeDisabled();
  }
 });
}
test('control labels use current typography and wrap on mobile',async({page})=>{await page.setViewportSize({width:320,height:700});await page.goto('/iframe.html?id=components-selection-checkbox--long-text&viewMode=story');await expect(page.locator('.fdoc-control__label')).toHaveCSS('font-size','14px');await expect(page.locator('.fdoc-control__label')).toHaveCSS('line-height','20px');await expect(page.locator('.fdoc-control-row')).toHaveCSS('gap','16px');const row=await page.locator('.fdoc-control-row').boundingBox();expect(row?.width).toBeLessThanOrEqual(280);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);});
test('radio group native keyboard skips disabled and checkbox mixed uses Space',async({page})=>{await page.goto('/iframe.html?id=components-selection-radiogroup--default&viewMode=story');const first=page.getByRole('radio',{name:'Электронная почта'});await expect(first).toBeVisible();await page.keyboard.press('Tab');await expect(first).toBeFocused();await page.keyboard.press('ArrowDown');await expect(page.getByRole('radio',{name:'Сообщения на телефон'})).toBeChecked();await page.keyboard.press('ArrowDown');await expect(first).toBeChecked();await page.goto('/iframe.html?id=components-selection-checkbox--indeterminate&viewMode=story');const check=page.getByRole('checkbox');await expect(check).toHaveAttribute('aria-checked','mixed');await check.focus();await page.keyboard.press('Space');await expect(check).toBeChecked();});
test('link matrix uses external focus and text-only underline',async({page})=>{await page.goto('/iframe.html?id=components-actions-link--states&viewMode=story');for(const color of ['base','primary','accent','neutral','inverse']){const focus=page.locator(`a[data-color="${color}"][data-state=focused]`);await expect(focus).toHaveCSS('outline-width','4px');await expect(focus).toHaveCSS('outline-style','solid');const plain=page.locator(`a[data-color="${color}"][data-state=default]`);await expect(focus).toHaveCSS('color',await plain.evaluate(el=>getComputedStyle(el).color));await expect(focus.locator('.fdoc-link__text')).toHaveCSS('text-decoration-line','underline');await expect(focus.locator('.fdoc-icon')).toHaveCSS('text-decoration-line','none');} });
test('toggle arrows change selection once and preserve geometry',async({page})=>{await page.goto('/iframe.html?id=components-actions-buttontoggle--default&viewMode=story');const day=page.getByRole('radio',{name:'День'});await expect(day).toBeVisible();const before=await day.boundingBox();await page.keyboard.press('Tab');await page.keyboard.press('ArrowRight');const week=page.getByRole('radio',{name:'Неделя'});await expect(week).toBeFocused();await expect(week).toHaveAttribute('aria-checked','true');await page.keyboard.press('Enter');await expect(week).toHaveAttribute('aria-checked','true');expect(await day.boundingBox()).toEqual(before);});
test('tooltip flips at edge and stays visible within viewport',async({page})=>{await page.setViewportSize({width:320,height:700});await page.goto('/iframe.html?id=components-overlays-tooltip--at-edge&viewMode=story');await page.getByRole('button').focus();const tip=page.getByRole('tooltip');await expect(tip).toBeVisible();const bounds=await tip.boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(8);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(312);expect(bounds!.y).toBeGreaterThanOrEqual(8);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(692);await expect(tip).toHaveCSS('padding','8px');await expect(tip).toHaveCSS('border-radius','4px');await expect(page.getByRole('button')).toHaveAttribute('aria-describedby',await tip.getAttribute('id') as string);});
test('accordion group keeps one open and large becomes medium on mobile',async({page})=>{await page.goto('/iframe.html?id=components-navigation-accordiongroup--default&viewMode=story');const buttons=page.getByRole('button');await buttons.nth(0).click();await buttons.nth(1).click();await expect(buttons.nth(0)).toHaveAttribute('aria-expanded','false');await expect(buttons.nth(1)).toHaveAttribute('aria-expanded','true');await page.goto('/iframe.html?id=components-navigation-accordion--large&viewMode=story');await expect(page.locator('.fdoc-accordion__trigger')).toHaveCSS('padding','24px 24px 24px 32px');await page.setViewportSize({width:375,height:700});await expect(page.locator('.fdoc-accordion__trigger')).toHaveCSS('padding','16px 8px 16px 16px');await expect(page.locator('.fdoc-accordion__chevron')).toHaveCSS('width','40px');});
test('tabs preserve manual activation and reveal offscreen focus',async({page})=>{await page.goto('/iframe.html?id=components-navigation-tabs--overflow&viewMode=story');const first=page.getByRole('tab',{name:'Раздел 1',exact:true});await expect(first).toBeVisible();await first.focus();await page.keyboard.press('End');const last=page.getByRole('tab',{name:'Раздел 12',exact:true});await expect(last).toBeFocused();await expect(first).toHaveAttribute('aria-selected','true');await page.keyboard.press('Space');await expect(last).toHaveAttribute('aria-selected','true');await expect(page.getByRole('tabpanel')).toHaveText('Содержимое 12');const b=await last.boundingBox(),parent=await page.locator('.fdoc-tabs__list').boundingBox();expect(b!.x+b!.width).toBeLessThanOrEqual(parent!.x+parent!.width+1);await expect(last).toHaveCSS('height','48px');});
test('breadcrumbs removes collapsed links on mobile',async({page})=>{await page.goto('/iframe.html?id=components-navigation-breadcrumbs--deep&viewMode=story');await expect(page.getByRole('link')).toHaveCount(4);await page.setViewportSize({width:320,height:700});await expect(page.getByRole('link')).toHaveCount(1);await expect(page.locator('[aria-current=page]')).toHaveAttribute('title','Договор с длинным названием без ручного сокращения');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);});
test('pagination updates counter and keeps long numbers within container',async({page})=>{await page.goto('/iframe.html?id=components-navigation-pagination--interactive&viewMode=story');await page.getByRole('button',{name:'Следующая страница'}).click();await expect(page.locator('.fdoc-pagination__counter')).toHaveText('11—20 из 400');await page.goto('/iframe.html?id=components-navigation-pagination--long-numbers&viewMode=story');await expect(page.locator('.fdoc-pagination')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(1280);const root=await page.locator('.fdoc-pagination').boundingBox();const list=await page.locator('.fdoc-pagination__pages').boundingBox();expect(list!.width).toBeLessThanOrEqual(root!.width);await expect(page.getByRole('button',{name:'Страница 999998',exact:true})).toHaveCSS('height','32px');});
