import { cloneElement, useEffect, useId, useLayoutEffect, useRef, useState, type CSSProperties, type ReactElement, type ReactNode } from 'react';
import { createPortal } from 'react-dom';
import './Tooltip.css';
export interface TooltipProps { children:ReactElement<{'aria-describedby'?:string}>; content:ReactNode; type?:'string'|'area'|'area-max'; placement?:'top'|'bottom'|'left'|'right'|'top-start'|'top-end'|'bottom-start'|'bottom-end'|'left-start'|'left-end'|'right-start'|'right-end'; trigger?:'hover'|'focus'|'hover+focus'; delayShow?:number; delayHide?:number; disabled?:boolean; arrow?:boolean; maxWidth?:CSSProperties['maxWidth']; zIndex?:number; }
export function Tooltip({children,content,type='string',placement='top',trigger='hover+focus',delayShow=200,delayHide=120,disabled=false,arrow=false,maxWidth,zIndex}:TooltipProps) {
 const id=useId();const anchor=useRef<HTMLSpanElement>(null);const popup=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const pointer=useRef(false);const focus=useRef(false);const [open,setOpen]=useState(false);const [position,setPosition]=useState({left:0,top:0,side:'top',ready:false});
 function schedule(){if(timer.current)clearTimeout(timer.current);const show=!disabled&&((trigger!=='focus'&&pointer.current)||(trigger!=='hover'&&focus.current));timer.current=setTimeout(()=>setOpen(show),show?delayShow:delayHide);}
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 useLayoutEffect(()=>{if(!open||disabled)return;const update=()=>{const a=anchor.current?.getBoundingClientRect(),p=popup.current?.getBoundingClientRect();if(!a||!p)return;let [side,align]=placement.split('-');const gap=8;const vw=document.documentElement.clientWidth,vh=window.innerHeight;const room={top:a.top,bottom:vh-a.bottom,left:a.left,right:vw-a.right};const opposite:{[key:string]:string}={top:'bottom',bottom:'top',left:'right',right:'left'};const needed=side==='top'||side==='bottom'?p.height+gap:p.width+gap;if(room[side as keyof typeof room]<needed&&room[opposite[side] as keyof typeof room]>room[side as keyof typeof room])side=opposite[side];let left=(a.left+a.right-p.width)/2,top=(a.top+a.bottom-p.height)/2;if(side==='top'||side==='bottom'){top=side==='top'?a.top-p.height-gap:a.bottom+gap;if(align==='start')left=a.left;if(align==='end')left=a.right-p.width;}else{left=side==='left'?a.left-p.width-gap:a.right+gap;if(align==='start')top=a.top;if(align==='end')top=a.bottom-p.height;}setPosition({left:Math.max(gap,Math.min(left,vw-p.width-gap)),top:Math.max(gap,Math.min(top,vh-p.height-gap)),side,ready:true});};update();const observer=new ResizeObserver(update);if(anchor.current)observer.observe(anchor.current);if(popup.current)observer.observe(popup.current);window.addEventListener('resize',update);window.addEventListener('scroll',update,true);return()=>{observer.disconnect();window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true);};},[open,disabled,placement,content,type,maxWidth]);
 useEffect(()=>{if(disabled){if(timer.current)clearTimeout(timer.current);setOpen(false);}},[disabled]);
 const visible=open&&!disabled;
 return <><span className="fdoc-tooltip-anchor" ref={anchor} onMouseEnter={()=>{pointer.current=true;schedule();}} onMouseLeave={()=>{pointer.current=false;schedule();}} onFocus={()=>{focus.current=true;schedule();}} onBlur={()=>{focus.current=false;schedule();}}>{cloneElement(children,{'aria-describedby':[children.props['aria-describedby'],visible?id:null].filter(Boolean).join(' ')||undefined})}</span>{visible&&createPortal(<div ref={popup} id={id} role="tooltip" data-type={type} data-side={position.side} className="fdoc-tooltip" style={{left:position.left,top:position.top,visibility:position.ready?'visible':'hidden',maxWidth,zIndex}} onMouseEnter={()=>{pointer.current=true;schedule();}} onMouseLeave={()=>{pointer.current=false;schedule();}}>{content}{arrow&&<span className="fdoc-tooltip__arrow"/>}</div>,document.body)}</>;
}
